---
  deployment:
    tasks:
      - export DEPLOYPATH=/home/u8832552/public_html/development
      - export PRIVATEPATH=/home/u8832552/private_development
      - /bin/cp -r * $PRIVATEPATH
      - /bin/cp -rf public/* $DEPLOYPATH